# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14470bdabf62b97a5e86d41c1ce3dec34b1b67ca067cb3839cd52b4c867d6f1cf3d7c1cfb8e387d475e30b5ea387e15ea32f7ac1e560bb031357f4960625df87

test:
  secret_key_base: ca926b6dc3f6392493b4d49f60765b9c8eff9a9238022088a8295832c4a43ba6052649125a4b78b527cea11ce9cb001ff5a4f0d4765ae2628a9bc9817ace0f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
